import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Activity, ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Clock3, Cpu, Gauge, HardDrive, Images, KeyRound, Layers, ListVideo, MapPin, MemoryStick, Monitor, MoreHorizontal, Pencil, Radio, RefreshCw, RotateCw, Settings, Signal, Thermometer, Users, WifiOff, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { getScreen, type ScreenStatus } from "@/lib/screens-data";

export const Route = createFileRoute("/screens/$screenId")({
  head: ({ params }) => {
    const screen = getScreen(params.screenId);
    const title = screen ? `${screen.name} — Screens — Signage CMS` : "Screen unavailable — Signage CMS";
    const description = screen ? `Live status, playback and device health for ${screen.name}.` : "The requested screen could not be found.";
    return { meta: [
      { title }, { name: "description", content: description },
      { property: "og:title", content: title }, { property: "og:description", content: description },
      { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
    ] };
  },
  component: ScreenDetailPage,
});

const NAV_ITEMS = [
  { label: "Control Center", icon: Gauge, to: "/control-center" as const },
  { label: "Pulse", icon: Activity, to: "/pulse" as const },
  { label: "Screens", icon: Monitor, to: "/screens" as const },
  { label: "Schedules", icon: CalendarDays },
  { label: "Media", icon: Images, to: "/media" as const },
  { label: "Playlists", icon: ListVideo },
  { label: "Layouts", icon: Layers, to: "/layouts" as const },
  { label: "Licensing", icon: KeyRound },
  { label: "Users", icon: Users },
];
const SIGNAL_POINTS = [72, 78, 75, 84, 82, 88, 86, 93, 90, 95, 92, 97, 94, 99, 96, 98, 97, 99];

function ScreenDetailPage() {
  const { screenId } = Route.useParams();
  const screen = getScreen(screenId);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [range, setRange] = useState<"Live" | "24 hours" | "7 days">("Live");
  const [restarting, setRestarting] = useState(false);
  const navAction = (label: string) => toast(label, { description: "This section is not connected yet." });
  if (!screen) return <div className="grid min-h-screen place-items-center bg-surface px-6 text-center text-foreground"><div><Monitor className="mx-auto size-10 text-muted-foreground" /><h1 className="mt-4 font-display text-xl font-semibold">Screen unavailable</h1><p className="mt-2 text-sm text-muted-foreground">This screen may have been removed or its link has changed.</p><Button asChild className="mt-5"><Link to="/screens"><ArrowLeft className="size-4" />Back to screens</Link></Button></div></div>;
  const isOffline = screen.status === "offline";

  const restart = () => { setRestarting(true); toast.success("Restart command sent", { description: `${screen.name} will reconnect automatically.` }); window.setTimeout(() => setRestarting(false), 1200); };
  return <div className="flex h-screen min-w-[940px] overflow-hidden bg-surface text-foreground">
    <Toaster />
    <aside className={cn("relative flex h-screen shrink-0 border-r border-border bg-card transition-[width] duration-200", sidebarOpen ? "w-72" : "w-16")}>
      <div className="flex w-16 shrink-0 flex-col items-center border-r border-border bg-surface py-3"><Link to="/control-center" aria-label="Control Centre home" className="mb-5 grid size-9 place-items-center rounded-md bg-primary text-primary-foreground shadow-sm"><Layers className="size-4" /></Link><nav className="flex flex-col items-center gap-0.5">{NAV_ITEMS.map((item) => item.to ? <Button key={item.label} asChild variant="ghost" size="icon" className={cn("size-9 text-muted-foreground", item.to === "/screens" && "bg-primary/15 text-primary hover:bg-primary/20 hover:text-primary")}><Link to={item.to} title={item.label} aria-label={item.label}><item.icon className="size-4" /></Link></Button> : <Button key={item.label} variant="ghost" size="icon" title={item.label} onClick={() => navAction(item.label)} className="size-9 text-muted-foreground"><item.icon className="size-4" /></Button>)}</nav><Button variant="ghost" size="icon" title="Settings" className="mt-auto size-9 text-muted-foreground" onClick={() => navAction("Settings")}><Settings className="size-4" /></Button></div>
      {sidebarOpen && <div className="flex min-w-0 flex-1 flex-col overflow-y-auto px-4 py-3"><div className="mb-5 flex h-9 items-center justify-between"><div className="flex items-baseline gap-2"><p className="font-display text-sm font-semibold">Signage CMS</p><p className="label-caps">Workspace</p></div><Button variant="ghost" size="icon" onClick={() => setSidebarOpen(false)} aria-label="Collapse sidebar" className="size-7 text-muted-foreground"><ChevronLeft className="size-3.5" /></Button></div><nav className="flex flex-col gap-0.5">{NAV_ITEMS.map((item) => item.to ? <Button key={item.label} asChild variant="ghost" className={cn("h-9 w-full justify-start gap-3 px-2 text-sm font-normal text-muted-foreground", item.to === "/screens" && "bg-primary/15 font-semibold text-primary hover:bg-primary/20 hover:text-primary")}><Link to={item.to}><item.icon className="size-4" />{item.label}</Link></Button> : <Button key={item.label} variant="ghost" onClick={() => navAction(item.label)} className="h-9 w-full justify-start gap-3 px-2 text-sm font-normal text-muted-foreground"><item.icon className="size-4" />{item.label}</Button>)}</nav><section className="mt-5 border-t border-border pt-5"><p className="label-caps px-2">Selected screen</p><div className="mt-3 rounded-md border border-border bg-surface p-3"><div className="flex items-center gap-2"><StatusDot status={screen.status} /><p className="truncate text-xs font-semibold">{screen.name}</p></div><p className="mt-1.5 text-[10px] text-muted-foreground">{screen.location} · {screen.area}</p><p className="mt-3 font-mono text-[9px] text-muted-foreground">Last signal {screen.lastSeen}</p></div></section><div className="mt-auto border-t border-border pt-4"><p className="label-caps">Player identity</p><p className="mt-2 font-mono text-[10px]">{screen.ip}</p><p className="mt-1 text-[10px] text-muted-foreground">{screen.player}</p></div></div>}
      {!sidebarOpen && <Button variant="ghost" size="icon" onClick={() => setSidebarOpen(true)} aria-label="Expand sidebar" className="absolute left-11 top-3 size-7 border border-border bg-card text-muted-foreground shadow-sm"><ChevronRight className="size-3.5" /></Button>}
    </aside>
    <div className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 shrink-0 items-center gap-3 border-b border-border bg-card px-6"><Button asChild variant="ghost" size="icon" className="size-8"><Link to="/screens" aria-label="Back to screens"><ArrowLeft className="size-4" /></Link></Button><div className="h-7 border-l border-border" /><div><div className="flex items-center gap-2"><h1 className="font-display text-base font-semibold">{screen.name}</h1><span className={cn("flex items-center gap-1 rounded-sm px-1.5 py-0.5 font-mono text-[8px] uppercase", screen.status === "online" ? "bg-accent/15 text-accent" : screen.status === "attention" ? "bg-primary/15 text-primary" : "bg-destructive/10 text-destructive")}><StatusDot status={screen.status} />{screen.status}</span></div><p className="text-xs text-muted-foreground">{screen.location} · {screen.area}</p></div><div className="ml-auto flex gap-2"><Button variant="outline" size="sm" onClick={() => toast.success("Content refresh queued", { description: "Latest assets will be checked and synchronized." })}><RefreshCw className="size-3.5" />Refresh content</Button><Button size="sm" onClick={restart} disabled={restarting}><RotateCw className={cn("size-3.5", restarting && "animate-spin")} />{restarting ? "Restarting…" : "Restart player"}</Button><Button variant="ghost" size="icon" aria-label="More screen actions" className="size-8"><MoreHorizontal className="size-4" /></Button></div></header>
      <main className="min-w-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-[1440px] px-6 py-6">
        {isOffline && <section className="mb-5 flex items-center gap-3 border border-destructive/30 bg-destructive/5 px-4 py-3"><div className="grid size-8 place-items-center rounded-md bg-destructive/10 text-destructive"><WifiOff className="size-4" /></div><div><p className="text-xs font-semibold">Player connection lost</p><p className="mt-0.5 text-[11px] text-muted-foreground">No heartbeat received for 14 minutes. Power and network checks are recommended.</p></div><Button variant="outline" size="sm" className="ml-auto" onClick={() => toast("Diagnostic started", { description: "Testing the last known player connection." })}>Run diagnostic</Button></section>}
        <div className="grid grid-cols-[minmax(0,1.45fr)_minmax(320px,.75fr)] gap-5"><div className="space-y-5">
          <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><div className="flex items-center gap-2"><Radio className="size-4 text-accent" /><h2 className="font-display text-sm font-semibold">Live playback</h2></div><p className="mt-1 text-xs text-muted-foreground">What the audience should see now</p></div><span className="font-mono text-[9px] text-muted-foreground">{screen.resolution}</span></div><div className="bg-surface p-6"><div className={cn("relative mx-auto overflow-hidden border-[6px] border-foreground/80 bg-secondary shadow-panel", screen.orientation === "Portrait" ? "aspect-[9/16] h-[340px]" : screen.orientation === "Ultrawide" ? "aspect-[32/9] w-full" : "aspect-video w-full")}><div className="absolute inset-0 grid grid-cols-[1.6fr_1fr]"><div className="flex flex-col justify-end bg-accent/15 p-6"><p className="label-caps text-accent">Current feature</p><p className="mt-2 font-display text-xl font-semibold">{screen.currentContent}</p><p className="mt-1 text-xs text-muted-foreground">{screen.layout}</p></div><div className="grid grid-rows-2"><div className="flex items-end bg-primary/20 p-4"><span className="font-mono text-[10px]">10:42</span></div><div className="border-t border-border bg-card p-4"><p className="text-[10px] font-medium">Welcome to {screen.location}</p></div></div></div>{isOffline && <div className="absolute inset-0 grid place-items-center bg-card/85"><div className="text-center"><WifiOff className="mx-auto size-7 text-destructive" /><p className="mt-2 text-xs font-semibold">Preview unavailable</p></div></div>}</div></div><div className="grid grid-cols-3 border-t border-border"><PlaybackInfo label="Now playing" value={screen.currentContent} /><PlaybackInfo label="Layout" value={screen.layout} bordered /><PlaybackInfo label="Up next" value={screen.nextItem} bordered /></div></section>
          <section className="panel p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Signal className="size-4 text-accent" /><h2 className="font-display text-sm font-semibold">Connection quality</h2></div><p className="mt-1 text-xs text-muted-foreground">Heartbeat stability and delivery latency</p></div><div className="flex rounded-md border border-border bg-card p-1">{(["Live", "24 hours", "7 days"] as const).map((item) => <Button key={item} variant="ghost" size="sm" onClick={() => setRange(item)} className={cn("h-7 px-3 text-xs", range === item && "bg-secondary")}>{item}</Button>)}</div></div><div className="relative mt-5 h-32 border-b border-l border-border"><div className="absolute inset-0 flex flex-col justify-between">{[0,1,2,3].map((line) => <span key={line} className="border-t border-dashed border-border/70" />)}</div><div className="absolute inset-x-3 bottom-0 top-2 flex items-end gap-1.5">{SIGNAL_POINTS.map((point, index) => <div key={index} className="flex h-full flex-1 items-end"><div className={cn("w-full rounded-t-sm", isOffline && index > 13 ? "bg-destructive/40" : "bg-accent/35")} style={{ height: `${isOffline && index > 13 ? Math.max(4, 70 - index * 4) : point}%` }} /></div>)}</div></div><div className="mt-2 flex justify-between font-mono text-[9px] text-muted-foreground"><span>Earlier</span><span>−30 min</span><span>−15 min</span><span>Now</span></div></section>
          <section className="panel overflow-hidden"><div className="border-b border-border px-5 py-4"><h2 className="font-display text-sm font-semibold">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">Player and content events for this screen</p></div><ActivityRow icon={CheckCircle2} title="Playlist synchronized" detail={`${screen.layout} · 18 assets verified`} time="10:39" /><ActivityRow icon={RefreshCw} title="Content cache refreshed" detail="124 MB downloaded successfully" time="10:34" /><ActivityRow icon={Signal} title="Heartbeat received" detail={`${screen.signal || 0}% signal quality · ${screen.ip}`} time="10:32" /><ActivityRow icon={Clock3} title="Schedule advanced" detail={`Started ${screen.currentContent}`} time="10:30" /></section>
        </div><aside className="space-y-5">
          <section className="grid grid-cols-2 gap-3"><HealthStat icon={Cpu} label="CPU" value={`${screen.cpu}%`} tone={screen.cpu > 45 ? "primary" : "accent"} /><HealthStat icon={MemoryStick} label="Memory" value={`${screen.memory}%`} tone={screen.memory > 65 ? "primary" : "accent"} /><HealthStat icon={Thermometer} label="Temperature" value={screen.temperature ? `${screen.temperature}°C` : "—"} tone={screen.temperature > 55 ? "primary" : "accent"} /><HealthStat icon={HardDrive} label="Storage" value={`${screen.storage}%`} tone={screen.storage > 70 ? "primary" : "accent"} /></section>
          {screen.status === "attention" && <section className="overflow-hidden rounded-md border border-primary/35 bg-card shadow-panel"><div className="flex gap-3 border-b border-border bg-primary/10 p-4"><CircleAlert className="size-4 text-primary" /><div><p className="label-caps text-primary">Needs attention</p><h3 className="mt-1 text-sm font-semibold">Player resources are elevated</h3></div></div><div className="p-4"><p className="text-xs leading-relaxed text-muted-foreground">Clearing older cached campaigns can recover storage and improve playback stability.</p><Button size="sm" className="mt-4" onClick={() => toast.success("Cache optimized", { description: "Unused campaign files were cleared." })}><Zap className="size-3.5" />Optimize player</Button></div></section>}
          <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-4 py-3.5"><h2 className="font-display text-sm font-semibold">Device details</h2><Button variant="ghost" size="icon" aria-label="Edit device details" className="size-7" onClick={() => toast("Edit screen", { description: "Screen settings are ready to update." })}><Pencil className="size-3.5" /></Button></div><div className="p-4"><Detail label="Location" value={`${screen.location} · ${screen.area}`} icon={MapPin} /><Detail label="Resolution" value={screen.resolution} icon={Monitor} /><Detail label="Player" value={screen.player} icon={Cpu} /><Detail label="IP address" value={screen.ip} icon={Signal} /><Detail label="Uptime" value={screen.uptime} icon={Clock3} last /></div></section>
          <section className="panel overflow-hidden"><div className="border-b border-border px-4 py-3.5"><h2 className="font-display text-sm font-semibold">Assignment</h2></div><div className="p-4"><p className="label-caps">Active layout</p><p className="mt-2 text-sm font-semibold">{screen.layout}</p><p className="mt-1 text-[11px] text-muted-foreground">Scheduled content changes automatically throughout the day.</p><Button variant="outline" className="mt-4 w-full" onClick={() => toast("Assignment editor", { description: "Choose a layout, playlist or schedule." })}>Edit assignment</Button></div></section>
        </aside></div>
      </div></main>
    </div>
  </div>;
}

function StatusDot({ status }: { status: ScreenStatus }) { return <span className={cn("size-1.5 rounded-full", status === "online" ? "bg-accent" : status === "attention" ? "bg-primary" : "bg-destructive")} />; }
function PlaybackInfo({ label, value, bordered = false }: { label: string; value: string; bordered?: boolean }) { return <div className={cn("min-w-0 px-4 py-3", bordered && "border-l border-border")}><p className="label-caps">{label}</p><p className="mt-1 truncate text-[11px] font-medium">{value}</p></div>; }
function HealthStat({ icon: Icon, label, value, tone }: { icon: typeof Cpu; label: string; value: string; tone: "primary" | "accent" }) { return <div className="panel p-4"><div className="flex items-center justify-between"><p className="label-caps">{label}</p><Icon className={cn("size-4", tone === "primary" ? "text-primary" : "text-accent")} /></div><p className="mt-3 font-display text-xl font-semibold">{value}</p></div>; }
function Detail({ label, value, icon: Icon, last = false }: { label: string; value: string; icon: typeof MapPin; last?: boolean }) { return <div className={cn("flex items-center gap-3 py-3", !last && "border-b border-border")}><Icon className="size-3.5 text-muted-foreground" /><div className="min-w-0"><p className="label-caps">{label}</p><p className="mt-1 truncate text-[11px] font-medium">{value}</p></div></div>; }
function ActivityRow({ icon: Icon, title, detail, time }: { icon: typeof Signal; title: string; detail: string; time: string }) { return <div className="grid grid-cols-[32px_minmax(0,1fr)_auto] items-center gap-3 border-b border-border px-5 py-3 last:border-0"><div className="grid size-8 place-items-center rounded-md bg-secondary text-muted-foreground"><Icon className="size-3.5" /></div><div className="min-w-0"><p className="truncate text-xs font-medium">{title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{detail}</p></div><span className="font-mono text-[9px] text-muted-foreground">{time}</span></div>; }
