/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlCenterRouteImport } from './routes/control-center'
import { Route as LayoutsRouteImport } from './routes/layouts'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PulseRouteImport } from './routes/pulse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRoute = ControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsRoute = LayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/layouts': typeof LayoutsRoute
  '/media': typeof MediaRoute
  '/pulse': typeof PulseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/layouts': typeof LayoutsRoute
  '/media': typeof MediaRoute
  '/pulse': typeof PulseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-center': typeof ControlCenterRoute
  '/layouts': typeof LayoutsRoute
  '/media': typeof MediaRoute
  '/pulse': typeof PulseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control-center' | '/layouts' | '/media' | '/pulse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control-center' | '/layouts' | '/media' | '/pulse'
  id: '__root__' | '/' | '/control-center' | '/layouts' | '/media' | '/pulse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlCenterRoute: typeof ControlCenterRoute
  LayoutsRoute: typeof LayoutsRoute
  MediaRoute: typeof MediaRoute
  PulseRoute: typeof PulseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center': {
      id: '/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof ControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts': {
      id: '/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof LayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlCenterRoute: ControlCenterRoute,
  LayoutsRoute: LayoutsRoute,
  MediaRoute: MediaRoute,
  PulseRoute: PulseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
